/**
 * @file stdbr.h
 * @brief stdbr — standard library for Brazil.
 *
 * All strings returned by stdbr functions are heap-allocated
 * and must be freed with stdbr_free().
 * Enum-like input parameters use uint8_t so invalid values can be rejected
 * safely. Pass the corresponding STDBR_* constants; outputs use explicit
 * *_INVALID sentinels where NULL would otherwise be ambiguous.
 */

#ifndef STDBR_H
#define STDBR_H

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes for CEP validation.
 */
enum StdbrCepError
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_CEP_ERROR_OK = 0,
    STDBR_CEP_ERROR_INVALID_LENGTH = 1,
    STDBR_CEP_ERROR_INVALID_CHARACTER = 2,
    STDBR_CEP_ERROR_INVALID_FORMAT = 3,
};
#ifndef __cplusplus
typedef uint8_t StdbrCepError;
#endif // __cplusplus

/**
 * Postal region mapped by the first digit of a CEP.
 */
enum StdbrPostalRegion
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_POSTAL_REGION_GRAN_SAO_PAULO = 0,
    STDBR_POSTAL_REGION_INTERIOR_SAO_PAULO = 1,
    STDBR_POSTAL_REGION_RJ_ES = 2,
    STDBR_POSTAL_REGION_MG = 3,
    STDBR_POSTAL_REGION_BA_SE = 4,
    STDBR_POSTAL_REGION_PE_AL_PB_RN = 5,
    STDBR_POSTAL_REGION_CE_PI_MA_PA_AM_AC_AP_RR = 6,
    STDBR_POSTAL_REGION_DF_GO_TO_MT_MS_RO = 7,
    STDBR_POSTAL_REGION_PR_SC = 8,
    STDBR_POSTAL_REGION_RS = 9,
    /**
     * Sentinel returned when a postal region cannot be read.
     */
    STDBR_POSTAL_REGION_INVALID = 255,
};
#ifndef __cplusplus
typedef uint8_t StdbrPostalRegion;
#endif // __cplusplus

/**
 * Brazilian state.
 */
enum StdbrState
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_STATE_AC = 0,
    STDBR_STATE_AL = 1,
    STDBR_STATE_AM = 2,
    STDBR_STATE_AP = 3,
    STDBR_STATE_BA = 4,
    STDBR_STATE_CE = 5,
    STDBR_STATE_DF = 6,
    STDBR_STATE_ES = 7,
    STDBR_STATE_GO = 8,
    STDBR_STATE_MA = 9,
    STDBR_STATE_MG = 10,
    STDBR_STATE_MS = 11,
    STDBR_STATE_MT = 12,
    STDBR_STATE_PA = 13,
    STDBR_STATE_PB = 14,
    STDBR_STATE_PE = 15,
    STDBR_STATE_PI = 16,
    STDBR_STATE_PR = 17,
    STDBR_STATE_RJ = 18,
    STDBR_STATE_RN = 19,
    STDBR_STATE_RO = 20,
    STDBR_STATE_RR = 21,
    STDBR_STATE_RS = 22,
    STDBR_STATE_SC = 23,
    STDBR_STATE_SE = 24,
    STDBR_STATE_SP = 25,
    STDBR_STATE_TO = 26,
    /**
     * Sentinel returned when a state cannot be read.
     */
    STDBR_STATE_INVALID = 255,
};
#ifndef __cplusplus
typedef uint8_t StdbrState;
#endif // __cplusplus

/**
 * Error codes for CNPJ validation. `STDBR_CNPJ_ERROR_OK` (0) = success.
 */
enum StdbrCnpjError
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_CNPJ_ERROR_OK = 0,
    STDBR_CNPJ_ERROR_INVALID_LENGTH = 1,
    STDBR_CNPJ_ERROR_INVALID_CHARACTER = 2,
    STDBR_CNPJ_ERROR_INVALID_FORMAT = 3,
    STDBR_CNPJ_ERROR_ALL_CHARS_EQUAL = 4,
    STDBR_CNPJ_ERROR_INVALID_CHECK_DIGITS = 5,
};
#ifndef __cplusplus
typedef uint8_t StdbrCnpjError;
#endif // __cplusplus

/**
 * Whether the CNPJ uses only digits or also contains letters.
 */
enum StdbrCnpjKind
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_CNPJ_KIND_NUMERIC = 0,
    STDBR_CNPJ_KIND_ALPHANUMERIC = 1,
    /**
     * Sentinel returned when a CNPJ kind cannot be read.
     */
    STDBR_CNPJ_KIND_INVALID = 255,
};
#ifndef __cplusplus
typedef uint8_t StdbrCnpjKind;
#endif // __cplusplus

/**
 * Whether the establishment is Matriz or Filial.
 */
enum StdbrEstablishmentType
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_ESTABLISHMENT_TYPE_MATRIZ = 0,
    STDBR_ESTABLISHMENT_TYPE_FILIAL = 1,
    /**
     * Sentinel returned when an establishment type cannot be read.
     */
    STDBR_ESTABLISHMENT_TYPE_INVALID = 255,
};
#ifndef __cplusplus
typedef uint8_t StdbrEstablishmentType;
#endif // __cplusplus

/**
 * Error codes for CPF validation. `STDBR_CPF_ERROR_OK` (0) = success.
 */
enum StdbrCpfError
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_CPF_ERROR_OK = 0,
    STDBR_CPF_ERROR_INVALID_LENGTH = 1,
    STDBR_CPF_ERROR_INVALID_CHARACTER = 2,
    STDBR_CPF_ERROR_INVALID_FORMAT = 3,
    STDBR_CPF_ERROR_ALL_DIGITS_EQUAL = 4,
    STDBR_CPF_ERROR_INVALID_CHECK_DIGITS = 5,
};
#ifndef __cplusplus
typedef uint8_t StdbrCpfError;
#endif // __cplusplus

/**
 * Fiscal region mapped by the 9th digit of a CPF.
 */
enum StdbrFiscalRegion
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_FISCAL_REGION_RS = 0,
    STDBR_FISCAL_REGION_DF_GO_MS_MT_TO = 1,
    STDBR_FISCAL_REGION_AC_AM_AP_PA_RO_RR = 2,
    STDBR_FISCAL_REGION_CE_MA_PI = 3,
    STDBR_FISCAL_REGION_AL_PB_PE_RN = 4,
    STDBR_FISCAL_REGION_BA_SE = 5,
    STDBR_FISCAL_REGION_MG = 6,
    STDBR_FISCAL_REGION_ES_RJ = 7,
    STDBR_FISCAL_REGION_SP = 8,
    STDBR_FISCAL_REGION_PR_SC = 9,
    /**
     * Sentinel returned when a fiscal region cannot be read.
     */
    STDBR_FISCAL_REGION_INVALID = 255,
};
#ifndef __cplusplus
typedef uint8_t StdbrFiscalRegion;
#endif // __cplusplus

/**
 * Error codes for RG validation. `STDBR_RG_ERROR_OK` (0) = success.
 */
enum StdbrRgError
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_RG_ERROR_OK = 0,
    STDBR_RG_ERROR_INVALID_LENGTH = 1,
    STDBR_RG_ERROR_INVALID_CHARACTER = 2,
    STDBR_RG_ERROR_INVALID_FORMAT = 3,
    STDBR_RG_ERROR_INVALID_CHECK_DIGIT = 4,
    STDBR_RG_ERROR_UNSUPPORTED_UF_FOR_GENERATION = 5,
    STDBR_RG_ERROR_INVALID_UF = 6,
};
#ifndef __cplusplus
typedef uint8_t StdbrRgError;
#endif // __cplusplus

/**
 * Geographic region.
 */
enum StdbrRegion
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    STDBR_REGION_NORTE = 0,
    STDBR_REGION_NORDESTE = 1,
    STDBR_REGION_CENTRO_OESTE = 2,
    STDBR_REGION_SUDESTE = 3,
    STDBR_REGION_SUL = 4,
    /**
     * Sentinel returned for an invalid state.
     */
    STDBR_REGION_INVALID = 255,
};
#ifndef __cplusplus
typedef uint8_t StdbrRegion;
#endif // __cplusplus

typedef struct StdbrCep StdbrCep;

typedef struct StdbrCnpj StdbrCnpj;

typedef struct StdbrCpf StdbrCpf;

typedef struct StdbrMunicipio StdbrMunicipio;

/**
 * Opaque list of municipalities.
 */
typedef struct StdbrMunicipioList StdbrMunicipioList;

typedef struct StdbrRg StdbrRg;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Frees a string previously returned by stdbr functions.
 */
void stdbr_free(char *ptr);

/**
 * Parses a CEP string (strict). Returns `NULL` on failure.
 */
struct StdbrCep *stdbr_cep_parse(const char *raw, StdbrCepError *err);

/**
 * Generates a random valid CEP.
 */
struct StdbrCep *stdbr_cep_create(void);

/**
 * Generates a random CEP for a postal region, or `NULL` if `region` is invalid.
 */
struct StdbrCep *stdbr_cep_create_for_region(uint8_t region);

/**
 * Generates a CEP for a state, or `NULL` if `state` is invalid.
 */
struct StdbrCep *stdbr_cep_create_for_state(uint8_t state);

/**
 * Destroys a CEP handle. `NULL`-safe.
 */
void stdbr_cep_destroy(struct StdbrCep *cep);

/**
 * Unformatted 8-digit string. Caller frees with `stdbr_free`.
 */
char *stdbr_cep_as_str(const struct StdbrCep *cep);

/**
 * Formatted `#####-###`. Caller frees with `stdbr_free`.
 */
char *stdbr_cep_formatted(const struct StdbrCep *cep);

/**
 * Masked `#####-***`. Caller frees with `stdbr_free`.
 */
char *stdbr_cep_masked(const struct StdbrCep *cep);

/**
 * Returns the postal region, or `STDBR_POSTAL_REGION_INVALID` when `cep` is `NULL`.
 */
StdbrPostalRegion stdbr_cep_postal_region(const struct StdbrCep *cep);

/**
 * Returns the state. Writes the result to `*out` and returns `true`.
 */
bool stdbr_cep_state(const struct StdbrCep *cep, StdbrState *out);

/**
 * Lenient validation strips non-digits before checking.
 */
bool stdbr_cep_is_valid(const char *raw);

/**
 * Strict validation. Returns a `StdbrCepError` code.
 */
StdbrCepError stdbr_cep_is_valid_strict(const char *raw);

/**
 * Random valid CEP as 8-digit string. Caller frees with `stdbr_free`.
 */
char *stdbr_cep_generate(void);

/**
 * Formats as `#####-###`, or `NULL` if invalid. Caller frees with `stdbr_free`.
 */
char *stdbr_cep_format(const char *raw);

/**
 * Strips non-digit characters. Caller frees with `stdbr_free`.
 */
char *stdbr_cep_remove_symbols(const char *raw);

/**
 * Parses a CNPJ string (strict). Returns `NULL` on failure.
 */
struct StdbrCnpj *stdbr_cnpj_parse(const char *raw, StdbrCnpjError *err);

/**
 * Generates a random valid CNPJ, or `NULL` if `kind` is invalid.
 */
struct StdbrCnpj *stdbr_cnpj_create(uint8_t kind);

/**
 * Generates a Matriz CNPJ, or `NULL` if `kind` is invalid.
 */
struct StdbrCnpj *stdbr_cnpj_create_matriz(uint8_t kind);

/**
 * Destroys a CNPJ handle. `NULL`-safe.
 */
void stdbr_cnpj_destroy(struct StdbrCnpj *cnpj);

/**
 * Unformatted 14-character string. Caller frees with `stdbr_free`.
 */
char *stdbr_cnpj_as_str(const struct StdbrCnpj *cnpj);

/**
 * Formatted `XX.XXX.XXX/XXXX-DD`. Caller frees with `stdbr_free`.
 */
char *stdbr_cnpj_formatted(const struct StdbrCnpj *cnpj);

/**
 * Masked `XX.XXX.XXX/****-**`. Caller frees with `stdbr_free`.
 */
char *stdbr_cnpj_masked(const struct StdbrCnpj *cnpj);

/**
 * Returns the CNPJ kind, or `STDBR_CNPJ_KIND_INVALID` when `cnpj` is `NULL`.
 */
StdbrCnpjKind stdbr_cnpj_kind(const struct StdbrCnpj *cnpj);

/**
 * Returns the establishment type, or `STDBR_ESTABLISHMENT_TYPE_INVALID` when `cnpj` is `NULL`.
 */
StdbrEstablishmentType stdbr_cnpj_establishment_type(const struct StdbrCnpj *cnpj);

/**
 * Writes both check digits and returns `true`; returns `false` for any `NULL` pointer.
 */
bool stdbr_cnpj_check_digits(const struct StdbrCnpj *cnpj, uint8_t *d1, uint8_t *d2);

/**
 * Lenient validation strips non-alphanumeric chars before checking.
 */
bool stdbr_cnpj_is_valid(const char *raw);

/**
 * Strict validation. Returns a `StdbrCnpjError` code.
 */
StdbrCnpjError stdbr_cnpj_is_valid_strict(const char *raw);

/**
 * Returns a random CNPJ string, or `NULL` if `kind` is invalid. Caller frees with `stdbr_free`.
 */
char *stdbr_cnpj_generate(uint8_t kind);

/**
 * Formats as `XX.XXX.XXX/XXXX-DD`, or `NULL` if invalid. Caller frees with `stdbr_free`.
 */
char *stdbr_cnpj_format(const char *raw);

/**
 * Strips non-alphanumeric characters, uppercases. Caller frees with `stdbr_free`.
 */
char *stdbr_cnpj_remove_symbols(const char *raw);

/**
 * Computes check digits for a 12-character base. Returns `false` if invalid.
 */
bool stdbr_cnpj_compute_check_digits(const char *base, uint8_t *d1, uint8_t *d2);

/**
 * Parses a CPF string (strict). Returns `NULL` on failure.
 */
struct StdbrCpf *stdbr_cpf_parse(const char *raw, StdbrCpfError *err);

/**
 * Generates a random valid CPF.
 */
struct StdbrCpf *stdbr_cpf_create(void);

/**
 * Generates a random valid CPF for a fiscal region, or `NULL` if `region` is invalid.
 */
struct StdbrCpf *stdbr_cpf_create_for_region(uint8_t region);

/**
 * Destroys a CPF handle. `NULL`-safe.
 */
void stdbr_cpf_destroy(struct StdbrCpf *cpf);

/**
 * Unformatted 11-digit string. Caller frees with `stdbr_free`.
 */
char *stdbr_cpf_as_str(const struct StdbrCpf *cpf);

/**
 * Formatted `###.###.###-##`. Caller frees with `stdbr_free`.
 */
char *stdbr_cpf_formatted(const struct StdbrCpf *cpf);

/**
 * Masked `XXX.***.***-XX`. Caller frees with `stdbr_free`.
 */
char *stdbr_cpf_masked(const struct StdbrCpf *cpf);

/**
 * Returns the fiscal region, or `STDBR_FISCAL_REGION_INVALID` when `cpf` is `NULL`.
 */
StdbrFiscalRegion stdbr_cpf_fiscal_region(const struct StdbrCpf *cpf);

/**
 * Writes both check digits and returns `true`; returns `false` for any `NULL` pointer.
 */
bool stdbr_cpf_check_digits(const struct StdbrCpf *cpf, uint8_t *d1, uint8_t *d2);

/**
 * Lenient validation strips non-digits before checking.
 */
bool stdbr_cpf_is_valid(const char *raw);

/**
 * Strict validation. Returns a `StdbrCpfError` code.
 */
StdbrCpfError stdbr_cpf_is_valid_strict(const char *raw);

/**
 * Random valid CPF as 11-digit string. Caller frees with `stdbr_free`.
 */
char *stdbr_cpf_generate(void);

/**
 * Formats as `###.###.###-##`, or `NULL` if invalid. Caller frees with `stdbr_free`.
 */
char *stdbr_cpf_format(const char *raw);

/**
 * Strips non-digit characters. Caller frees with `stdbr_free`.
 */
char *stdbr_cpf_remove_symbols(const char *raw);

/**
 * Computes check digits for a 9-digit base. Returns `false` if invalid.
 */
bool stdbr_cpf_compute_check_digits(const char *base, uint8_t *d1, uint8_t *d2);

/**
 * Finds a municipio, or `NULL` if absent. Caller destroys it with `stdbr_municipio_destroy`.
 */
struct StdbrMunicipio *stdbr_municipio_from_ibge_code(uint32_t code);

/**
 * Gets a capital, or `NULL` for an invalid state. Caller destroys it with `stdbr_municipio_destroy`.
 */
struct StdbrMunicipio *stdbr_municipio_capital_of(uint8_t state);

/**
 * Destroys a municipio handle. `NULL`-safe.
 */
void stdbr_municipio_destroy(struct StdbrMunicipio *m);

/**
 * Returns the IBGE code, or the invalid code 0 when `m` is `NULL`.
 */
uint32_t stdbr_municipio_ibge_code(const struct StdbrMunicipio *m);

/**
 * Returns the name of a municipio. Caller frees with `stdbr_free`.
 */
char *stdbr_municipio_name(const struct StdbrMunicipio *m);

/**
 * Returns the state, or `STDBR_STATE_INVALID` when `m` is `NULL`.
 */
StdbrState stdbr_municipio_state(const struct StdbrMunicipio *m);

/**
 * Returns whether a municipio is a capital; returns `false` when `m` is `NULL`.
 */
bool stdbr_municipio_is_capital(const struct StdbrMunicipio *m);

/**
 * Total number of municipalities in the database.
 */
uint32_t stdbr_municipio_count(void);

/**
 * Returns a state list, or `NULL` for invalid state. Caller uses `stdbr_municipio_list_destroy`.
 */
struct StdbrMunicipioList *stdbr_municipio_by_state(uint8_t state);

/**
 * Searches by name, or returns `NULL` for a null/invalid query. Caller destroys the list with `stdbr_municipio_list_destroy`.
 */
struct StdbrMunicipioList *stdbr_municipio_search_by_name(const char *query);

/**
 * Returns the item count, or `UINT32_MAX` when `list` is `NULL`.
 */
uint32_t stdbr_municipio_list_count(const struct StdbrMunicipioList *list);

/**
 * Returns an independently owned municipio, or `NULL` for a null list/out-of-range index; destroy it with `stdbr_municipio_destroy`.
 */
struct StdbrMunicipio *stdbr_municipio_list_get(const struct StdbrMunicipioList *list,
                                                uint32_t index);

/**
 * Destroys a municipio list. `NULL`-safe.
 */
void stdbr_municipio_list_destroy(struct StdbrMunicipioList *list);

/**
 * Parses an RG; invalid `uf` returns `NULL` and `STDBR_RG_ERROR_INVALID_UF`.
 */
struct StdbrRg *stdbr_rg_parse(const char *raw, uint8_t uf, StdbrRgError *err);

/**
 * Creates an RG (currently SP only); invalid `uf` returns `NULL` and `STDBR_RG_ERROR_INVALID_UF`.
 */
struct StdbrRg *stdbr_rg_create_for_uf(uint8_t uf, StdbrRgError *err);

/**
 * Destroys an RG handle. `NULL`-safe.
 */
void stdbr_rg_destroy(struct StdbrRg *rg);

/**
 * Unformatted body. Caller frees with `stdbr_free`.
 */
char *stdbr_rg_as_str(const struct StdbrRg *rg);

/**
 * Formatted per the UF mask. Caller frees with `stdbr_free`.
 */
char *stdbr_rg_formatted(const struct StdbrRg *rg);

/**
 * Returns the issuing UF, or `STDBR_STATE_INVALID` when `rg` is `NULL`.
 */
StdbrState stdbr_rg_uf(const struct StdbrRg *rg);

/**
 * Writes the check digit to `*out`. Returns `true` if a digit exists
 */
bool stdbr_rg_check_digit(const struct StdbrRg *rg, uint8_t *out);

/**
 * Lenient validation strips separators; returns `false` for an invalid `uf`.
 */
bool stdbr_rg_is_valid(const char *raw, uint8_t uf);

/**
 * Strict validation; returns `STDBR_RG_ERROR_INVALID_UF` for an invalid `uf`.
 */
StdbrRgError stdbr_rg_is_valid_strict(const char *raw, uint8_t uf);

/**
 * Formats per the UF mask; returns `NULL` for invalid input or `uf`.
 */
char *stdbr_rg_format(const char *raw, uint8_t uf);

/**
 * Strips separators, or returns `NULL` for invalid input/`uf`. Caller frees with `stdbr_free`.
 */
char *stdbr_rg_remove_symbols(const char *raw, uint8_t uf);

/**
 * SP-only: writes the check digit and returns `true`; returns `false` for invalid input, pointer, or `uf`.
 */
bool stdbr_rg_compute_check_digit(const char *base,
                                  uint8_t uf,
                                  uint8_t *out);

/**
 * Generates an RG string; invalid `uf` returns `NULL` and `STDBR_RG_ERROR_INVALID_UF`. Caller frees with `stdbr_free`.
 */
char *stdbr_rg_generate(uint8_t uf,
                        StdbrRgError *err);

/**
 * Masked representation. Caller frees with `stdbr_free`. Returns `NULL` if
 */
char *stdbr_rg_masked(const struct StdbrRg *rg);

/**
 * Body without check digit. Caller frees with `stdbr_free`. Returns `NULL`
 */
char *stdbr_rg_body(const struct StdbrRg *rg);

/**
 * Returns the two-letter abbreviation, or `NULL` for an invalid state. Caller frees with `stdbr_free`.
 */
char *stdbr_state_abbreviation(uint8_t state);

/**
 * Returns the full name, or `NULL` for an invalid state. Caller frees with `stdbr_free`.
 */
char *stdbr_state_name(uint8_t state);

/**
 * Returns the geographic region, or `STDBR_REGION_INVALID` for an invalid state.
 */
StdbrRegion stdbr_state_region(uint8_t state);

/**
 * Parse a state from its two-letter abbreviation (case-insensitive).
 */
bool stdbr_state_from_abbreviation(const char *abbr, StdbrState *out);

/**
 * Writes all 27 states to `buf`; returns 27 on success or 0 when `buf` is `NULL`.
 */
uint32_t stdbr_all_states(StdbrState *buf);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* STDBR_H */
