module(name = "stdbr", version = "0.0.1")

bazel_dep(name = "rules_rust", version = "0.70.0")
bazel_dep(name = "rules_python", version = "1.6.3")
bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "platforms", version = "1.0.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(edition = "2024", versions = ["1.87.0"])
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
        "//core:Cargo.toml",
        "//bindings/ffi-c:Cargo.toml",
        "//bindings/nodejs:Cargo.toml",
        "//bindings/python:Cargo.toml",
        "//bindings/wasm:Cargo.toml",
        "//tools/parity_gen:Cargo.toml",
    ],
)
use_repo(crate, "crates")

cjson = use_extension("//tools:cjson_ext.bzl", "cjson")
use_repo(cjson, "cjson")
