load("@rules_rust//cargo:defs.bzl", "cargo_build_script")
load("@rules_rust//rust:defs.bzl", "rust_shared_library")

exports_files([
    "Cargo.toml",
    "tests/parity.mjs",
] + glob(["src/**/*.rs"]))

cargo_build_script(
    name = "napi_build_script",
    srcs = ["build.rs"],
    deps = ["@crates//:napi-build"],
)

rust_shared_library(
    name = "stdbr-napi",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    proc_macro_deps = ["@crates//:napi-derive"],
    visibility = ["//visibility:public"],
    deps = [
        ":napi_build_script",
        "//core:stdbr-core",
        "@crates//:napi",
    ],
)

genrule(
    name = "stdbr-node",
    srcs = [":stdbr-napi"],
    outs = ["stdbr.node"],
    cmd = "cp $< $@",
    visibility = ["//visibility:public"],
)
