/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'stdbr.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.android-arm64.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'stdbr.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.android-arm-eabi.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'stdbr.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'stdbr.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'stdbr.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'stdbr.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./stdbr.darwin-universal.node')
      } else {
        nativeBinding = require('@stdbr/stdbr-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'stdbr.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.darwin-x64.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'stdbr.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.darwin-arm64.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'stdbr.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./stdbr.freebsd-x64.node')
      } else {
        nativeBinding = require('@stdbr/stdbr-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-x64-musl.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stdbr.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stdbr.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@stdbr/stdbr-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'stdbr.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stdbr.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@stdbr/stdbr-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { PostalRegion, Cep, cepIsValid, cepIsValidStrict, cepFormat, cepRemoveSymbols, cepGenerate, cepGenerateForRegion, cepGenerateForState, CnpjKind, EstablishmentType, Cnpj, cnpjIsValid, cnpjIsValidStrict, cnpjFormat, cnpjRemoveSymbols, cnpjGenerate, cnpjComputeCheckDigits, FiscalRegion, Cpf, cpfIsValid, cpfIsValidStrict, cpfFormat, cpfRemoveSymbols, cpfGenerate, cpfComputeCheckDigits, Municipio, municipioFromIbgeCode, municipioCapitalOf, municipiosByState, municipioSearchByName, municipioCount, Rg, rgIsValid, rgIsValidStrict, rgFormat, rgRemoveSymbols, rgComputeCheckDigit, rgGenerate, Region, State, stateAbbreviation, stateName, stateRegion, stateFromAbbreviation, allStates } = nativeBinding

module.exports.PostalRegion = PostalRegion
module.exports.Cep = Cep
module.exports.cepIsValid = cepIsValid
module.exports.cepIsValidStrict = cepIsValidStrict
module.exports.cepFormat = cepFormat
module.exports.cepRemoveSymbols = cepRemoveSymbols
module.exports.cepGenerate = cepGenerate
module.exports.cepGenerateForRegion = cepGenerateForRegion
module.exports.cepGenerateForState = cepGenerateForState
module.exports.CnpjKind = CnpjKind
module.exports.EstablishmentType = EstablishmentType
module.exports.Cnpj = Cnpj
module.exports.cnpjIsValid = cnpjIsValid
module.exports.cnpjIsValidStrict = cnpjIsValidStrict
module.exports.cnpjFormat = cnpjFormat
module.exports.cnpjRemoveSymbols = cnpjRemoveSymbols
module.exports.cnpjGenerate = cnpjGenerate
module.exports.cnpjComputeCheckDigits = cnpjComputeCheckDigits
module.exports.FiscalRegion = FiscalRegion
module.exports.Cpf = Cpf
module.exports.cpfIsValid = cpfIsValid
module.exports.cpfIsValidStrict = cpfIsValidStrict
module.exports.cpfFormat = cpfFormat
module.exports.cpfRemoveSymbols = cpfRemoveSymbols
module.exports.cpfGenerate = cpfGenerate
module.exports.cpfComputeCheckDigits = cpfComputeCheckDigits
module.exports.Municipio = Municipio
module.exports.municipioFromIbgeCode = municipioFromIbgeCode
module.exports.municipioCapitalOf = municipioCapitalOf
module.exports.municipiosByState = municipiosByState
module.exports.municipioSearchByName = municipioSearchByName
module.exports.municipioCount = municipioCount
module.exports.Rg = Rg
module.exports.rgIsValid = rgIsValid
module.exports.rgIsValidStrict = rgIsValidStrict
module.exports.rgFormat = rgFormat
module.exports.rgRemoveSymbols = rgRemoveSymbols
module.exports.rgComputeCheckDigit = rgComputeCheckDigit
module.exports.rgGenerate = rgGenerate
module.exports.Region = Region
module.exports.State = State
module.exports.stateAbbreviation = stateAbbreviation
module.exports.stateName = stateName
module.exports.stateRegion = stateRegion
module.exports.stateFromAbbreviation = stateFromAbbreviation
module.exports.allStates = allStates
