/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum PostalRegion {
  GranSaoPaulo = 0,
  InteriorSaoPaulo = 1,
  RjEs = 2,
  Mg = 3,
  BaSe = 4,
  PeAlPbRn = 5,
  CePiMaPaAmAcApRr = 6,
  DfGoToMtMsRo = 7,
  PrSc = 8,
  Rs = 9
}
/** Lenient CEP validation (strips non-digit characters first). */
export declare function cepIsValid(cep: string): boolean
/** Strict CEP validation (accepts only `#####-###` or `########`). */
export declare function cepIsValidStrict(cep: string): void
/**
 * Format a CEP string as `#####-###`.
 * Returns `null` if the input doesn't contain exactly 8 digits.
 */
export declare function cepFormat(cep: string): string | null
/** Remove all non-digit characters from a CEP string. */
export declare function cepRemoveSymbols(cep: string): string
/** Generate a random valid CEP as an 8-digit string. */
export declare function cepGenerate(): string
/** Generate a random CEP for a given postal region. */
export declare function cepGenerateForRegion(region: PostalRegion): string
/** Generate a random CEP within the range of a given state. */
export declare function cepGenerateForState(state: State): string
export const enum CnpjKind {
  Numeric = 0,
  Alphanumeric = 1
}
export const enum EstablishmentType {
  Matriz = 0,
  Filial = 1
}
/** Lenient CNPJ validation (strips non-alphanumeric characters first). */
export declare function cnpjIsValid(cnpj: string): boolean
/** Strict CNPJ validation (accepts only `XX.XXX.XXX/XXXX-DD` or 14 raw characters). */
export declare function cnpjIsValidStrict(cnpj: string): void
/**
 * Format a CNPJ string as `XX.XXX.XXX/XXXX-DD`.
 * Returns `null` if the input is not a valid 14-character CNPJ.
 */
export declare function cnpjFormat(cnpj: string): string | null
/** Remove all non-alphanumeric characters from a CNPJ string, uppercase. */
export declare function cnpjRemoveSymbols(cnpj: string): string
/** Generate a random valid CNPJ as a 14-character string. */
export declare function cnpjGenerate(kind: CnpjKind): string
/**
 * Compute check digits for a 12-character CNPJ base.
 * Returns `null` if the input is invalid.
 */
export declare function cnpjComputeCheckDigits(base: string): Array<number> | null
export const enum FiscalRegion {
  Rs = 0,
  DfGoMsMtTo = 1,
  AcAmApPaRoRr = 2,
  CeMaPi = 3,
  AlPbPeRn = 4,
  BaSe = 5,
  Mg = 6,
  EsRj = 7,
  Sp = 8,
  PrSc = 9
}
/** Lenient CPF validation (strips non-digit characters first). */
export declare function cpfIsValid(cpf: string): boolean
/** Strict CPF validation (accepts only `###.###.###-##` or `###########`). */
export declare function cpfIsValidStrict(cpf: string): void
/**
 * Format a CPF string as `###.###.###-##`.
 * Returns `null` if the input doesn't contain exactly 11 digits.
 */
export declare function cpfFormat(cpf: string): string | null
/** Remove all non-digit characters from a CPF string. */
export declare function cpfRemoveSymbols(cpf: string): string
/** Generate a random valid CPF as an 11-digit string. */
export declare function cpfGenerate(): string
/**
 * Compute check digits for a 9-digit CPF base.
 * Returns `null` if the input is invalid.
 */
export declare function cpfComputeCheckDigits(base: string): Array<number> | null
/** Find a municipality by its IBGE code. */
export declare function municipioFromIbgeCode(code: number): Municipio | null
/** Get the capital of a given state. */
export declare function municipioCapitalOf(state: State): Municipio
/** Returns all municipalities in a given state. */
export declare function municipiosByState(state: State): Array<Municipio>
/** Find municipalities whose name contains the given substring (case-insensitive). */
export declare function municipioSearchByName(query: string): Array<Municipio>
/** Total number of municipalities. */
export declare function municipioCount(): number
/** Lenient RG validation (strips symbols first). */
export declare function rgIsValid(rg: string, uf: State): boolean
/** Strict RG validation (canonical mask or unformatted body only). */
export declare function rgIsValidStrict(rg: string, uf: State): void
/** Format an RG with the per-UF mask. Returns `null` if length is wrong. */
export declare function rgFormat(rg: string, uf: State): string | null
/** Strip separators. For SP, preserves a trailing 'X'. */
export declare function rgRemoveSymbols(rg: string, uf: State): string
/**
 * SP-only: compute the check digit for an 8-digit base. Returns 10 for the
 * `'X'` terminator. `null` for non-SP UFs or wrong length.
 */
export declare function rgComputeCheckDigit(base: string, uf: State): number | null
/** Generate a random valid RG (unformatted body). Currently SP only. */
export declare function rgGenerate(uf: State): string
export const enum Region {
  Norte = 0,
  Nordeste = 1,
  CentroOeste = 2,
  Sudeste = 3,
  Sul = 4
}
export const enum State {
  AC = 0,
  AL = 1,
  AM = 2,
  AP = 3,
  BA = 4,
  CE = 5,
  DF = 6,
  ES = 7,
  GO = 8,
  MA = 9,
  MG = 10,
  MS = 11,
  MT = 12,
  PA = 13,
  PB = 14,
  PE = 15,
  PI = 16,
  PR = 17,
  RJ = 18,
  RN = 19,
  RO = 20,
  RR = 21,
  RS = 22,
  SC = 23,
  SE = 24,
  SP = 25,
  TO = 26
}
/** Get the abbreviation of a state (e.g. "SP"). */
export declare function stateAbbreviation(state: State): string
/** Get the full name of a state (e.g. "São Paulo"). */
export declare function stateName(state: State): string
/** Get the geographic region of a state. */
export declare function stateRegion(state: State): Region
/** Parse a state from its two-letter abbreviation (case-insensitive). */
export declare function stateFromAbbreviation(abbr: string): State | null
/** Returns all 27 Brazilian states. */
export declare function allStates(): Array<State>
export declare class Cep {
  /** Parse a CEP string (accepts `#####-###` or `########`). */
  static parse(raw: string): Cep
  /** Generate a random valid CEP. */
  static generate(): Cep
  /** Generate a random CEP for a given postal region. */
  static generateForRegion(region: PostalRegion): Cep
  /** Generate a random CEP within the range of a given state. */
  static generateForState(state: State): Cep
  /** Unformatted 8-digit string. */
  asStr(): string
  /** Formatted as `#####-###`. */
  formatted(): string
  /** Masked as `#####-***`. */
  masked(): string
  /** Postal region derived from the 1st digit. */
  get postalRegion(): PostalRegion
  /** State lookup by CEP range. */
  get state(): State | null
}
export declare class Cnpj {
  /** Parse a CNPJ string (accepts `XX.XXX.XXX/XXXX-DD` or 14 raw characters). */
  static parse(raw: string): Cnpj
  /** Generate a random valid CNPJ. */
  static generate(kind: CnpjKind): Cnpj
  /** Generate a random valid CNPJ with ordem "0001" (Matriz). */
  static generateMatriz(kind: CnpjKind): Cnpj
  /** Unformatted 14-character string. */
  asStr(): string
  /** Formatted as `XX.XXX.XXX/XXXX-DD`. */
  formatted(): string
  /** Masked as `XX.XXX.XXX/****-**`. */
  masked(): string
  /** Root (positions 1-8): identifies the company. */
  raiz(): string
  /** Order (positions 9-12): identifies the establishment. */
  ordem(): string
  /** Whether the CNPJ is numeric or alphanumeric. */
  get kind(): CnpjKind
  /** Whether this is Matriz or Filial. */
  get establishmentType(): EstablishmentType
  /** The two check digits as `[d1, d2]`. */
  get checkDigits(): Array<number>
}
export declare class Cpf {
  /** Parse a CPF string (accepts `###.###.###-##` or `###########`). */
  static parse(raw: string): Cpf
  /** Generate a random valid CPF. */
  static generate(): Cpf
  /** Generate a random valid CPF for a specific fiscal region. */
  static generateForRegion(region: FiscalRegion): Cpf
  /** Unformatted 11-digit string. */
  asStr(): string
  /** Formatted as `###.###.###-##`. */
  formatted(): string
  /** Masked as `XXX.***.***-XX`. */
  masked(): string
  /** Fiscal region derived from the 9th digit. */
  get fiscalRegion(): FiscalRegion
  /** The two check digits as `[d1, d2]`. */
  get checkDigits(): Array<number>
}
export declare class Municipio {
  /** IBGE 7-digit code. */
  get ibgeCode(): number
  /** Municipality name. */
  get name(): string
  /** State this municipality belongs to. */
  get state(): State
  /** Whether this municipality is a state capital. */
  get isCapital(): boolean
}
export declare class Rg {
  /**
   * Parse an RG string for the given UF (accepts the canonical mask or
   * unformatted body).
   */
  static parse(raw: string, uf: State): Rg
  /** Generate a random valid RG. Currently SP only; other UFs return an error. */
  static generate(uf: State): Rg
  /** Unformatted body (digits, with optional trailing 'X' for SP). */
  asStr(): string
  /** Formatted per the UF mask (or raw body if no mask is defined). */
  formatted(): string
  /** Masked representation — first 2 digits visible, rest masked. */
  masked(): string
  /** Body without check digit (SP: 8-digit base; others: full string). */
  body(): string
  /** Issuing UF. */
  get uf(): State
  /**
   * Check digit (`Some(0..=9)` for digits, `Some(10)` for SP `'X'`,
   * `null` for UFs without a verified algorithm).
   */
  get checkDigit(): number | null
}
