[package]
name = "stdbr-core"
version = "0.0.7"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["std"]
std = []

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
