[package]
name = "stdbr-python"
version = "0.3.7"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords.workspace = true
categories.workspace = true

[lib]
name = "stdbr"
crate-type = ["cdylib"]

[dependencies]
stdbr-core = { path = "../../core" }
pyo3 = { version = "0.29", features = ["abi3-py39"] }

[lints]
workspace = true
