[package]
name = "stdbr-python"
version = "0.0.5"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "stdbr"
crate-type = ["cdylib"]

[dependencies]
stdbr-core = { path = "../../core" }
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py39"] }

[lints]
workspace = true
