# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing
from enum import Enum, auto

class Cep:
    postal_region: PostalRegion
    state: typing.Optional[State]
    @staticmethod
    def parse(raw:str) -> Cep:
        r"""
        Parse a CEP string (accepts `#####-###` or `########`).
        """
        ...

    @staticmethod
    def generate() -> Cep:
        r"""
        Generate a random valid CEP.
        """
        ...

    @staticmethod
    def generate_for_region(region:PostalRegion) -> Cep:
        r"""
        Generate a random CEP for a given postal region.
        """
        ...

    @staticmethod
    def generate_for_state(state:State) -> Cep:
        r"""
        Generate a random CEP within the range of a given state.
        """
        ...

    def as_str(self) -> str:
        r"""
        Unformatted 8-digit string.
        """
        ...

    def formatted(self) -> str:
        r"""
        Formatted as `#####-###`.
        """
        ...

    def masked(self) -> str:
        r"""
        Masked as `#####-***`.
        """
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...


class Cnpj:
    kind: CnpjKind
    establishment_type: EstablishmentType
    check_digits: tuple[int, int]
    @staticmethod
    def parse(raw:str) -> Cnpj:
        r"""
        Parse a CNPJ string (accepts `XX.XXX.XXX/XXXX-DD` or 14 raw characters).
        """
        ...

    @staticmethod
    def generate(kind:CnpjKind) -> Cnpj:
        r"""
        Generate a random valid CNPJ.
        """
        ...

    @staticmethod
    def generate_matriz(kind:CnpjKind) -> Cnpj:
        r"""
        Generate a random valid CNPJ with ordem "0001" (Matriz).
        """
        ...

    def as_str(self) -> str:
        r"""
        Unformatted 14-character string.
        """
        ...

    def formatted(self) -> str:
        r"""
        Formatted as `XX.XXX.XXX/XXXX-DD`.
        """
        ...

    def masked(self) -> str:
        r"""
        Masked as `XX.XXX.XXX/****-**`.
        """
        ...

    def raiz(self) -> str:
        r"""
        Root (positions 1-8): identifies the company.
        """
        ...

    def ordem(self) -> str:
        r"""
        Order (positions 9-12): identifies the establishment.
        """
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...


class Cpf:
    fiscal_region: FiscalRegion
    check_digits: tuple[int, int]
    @staticmethod
    def parse(raw:str) -> Cpf:
        r"""
        Parse a CPF string (accepts `###.###.###-##` or `###########`).
        """
        ...

    @staticmethod
    def generate() -> Cpf:
        r"""
        Generate a random valid CPF.
        """
        ...

    @staticmethod
    def generate_for_region(region:FiscalRegion) -> Cpf:
        r"""
        Generate a random valid CPF for a specific fiscal region.
        """
        ...

    def as_str(self) -> str:
        r"""
        Unformatted 11-digit string.
        """
        ...

    def formatted(self) -> str:
        r"""
        Formatted as `###.###.###-##`.
        """
        ...

    def masked(self) -> str:
        r"""
        Masked as `XXX.***.***-XX`.
        """
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...


class Rg:
    uf: State
    check_digit: typing.Optional[int]
    @staticmethod
    def parse(raw:str, uf:State) -> Rg:
        r"""
        Parse an RG string for the given UF.
        """
        ...

    @staticmethod
    def generate(uf:State) -> Rg:
        r"""
        Generate a random valid RG. Currently SP only; other UFs raise ValueError.
        """
        ...

    def as_str(self) -> str:
        r"""
        Unformatted body (digits, optionally trailing 'X' for SP).
        """
        ...

    def formatted(self) -> str:
        r"""
        Formatted per the UF mask.
        """
        ...

    def masked(self) -> str:
        r"""
        Masked representation — first 2 digits visible, rest masked.
        """
        ...

    def body(self) -> str:
        r"""
        Body without check digit (SP: 8-digit base; others: full string).
        """
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...


class Municipio:
    ibge_code: int
    name: str
    state: State
    is_capital: bool
    def __str__(self) -> str:
        ...

    def __repr__(self) -> str:
        ...


class CnpjKind(Enum):
    Numeric = auto()
    Alphanumeric = auto()

class EstablishmentType(Enum):
    Matriz = auto()
    Filial = auto()

class FiscalRegion(Enum):
    Rs = auto()
    DfGoMsMtTo = auto()
    AcAmApPaRoRr = auto()
    CeMaPi = auto()
    AlPbPeRn = auto()
    BaSe = auto()
    Mg = auto()
    EsRj = auto()
    Sp = auto()
    PrSc = auto()

class PostalRegion(Enum):
    GranSaoPaulo = auto()
    InteriorSaoPaulo = auto()
    RjEs = auto()
    Mg = auto()
    BaSe = auto()
    PeAlPbRn = auto()
    CePiMaPaAmAcApRr = auto()
    DfGoToMtMsRo = auto()
    PrSc = auto()
    Rs = auto()

class Region(Enum):
    Norte = auto()
    Nordeste = auto()
    CentroOeste = auto()
    Sudeste = auto()
    Sul = auto()

class State(Enum):
    AC = auto()
    AL = auto()
    AM = auto()
    AP = auto()
    BA = auto()
    CE = auto()
    DF = auto()
    ES = auto()
    GO = auto()
    MA = auto()
    MG = auto()
    MS = auto()
    MT = auto()
    PA = auto()
    PB = auto()
    PE = auto()
    PI = auto()
    PR = auto()
    RJ = auto()
    RN = auto()
    RO = auto()
    RR = auto()
    RS = auto()
    SC = auto()
    SE = auto()
    SP = auto()
    TO = auto()

def all_states() -> list[State]:
    r"""
    Returns all 27 Brazilian states.
    """
    ...

def cep_format(cep:str) -> typing.Optional[str]:
    r"""
    Format a CEP string as `#####-###`.
    Returns `None` if the input doesn't contain exactly 8 digits.
    """
    ...

def cep_generate() -> str:
    r"""
    Generate a random valid CEP as an 8-digit string.
    """
    ...

def cep_generate_for_region(region:PostalRegion) -> str:
    r"""
    Generate a random CEP for a given postal region.
    """
    ...

def cep_generate_for_state(state:State) -> str:
    r"""
    Generate a random CEP within the range of a given state.
    """
    ...

def cep_is_valid(cep:str) -> bool:
    r"""
    Lenient CEP validation (strips non-digit characters first).
    """
    ...

def cep_is_valid_strict(cep:str) -> None:
    r"""
    Strict CEP validation (accepts only `#####-###` or `########`).
    """
    ...

def cep_remove_symbols(cep:str) -> str:
    r"""
    Remove all non-digit characters from a CEP string.
    """
    ...

def cnpj_compute_check_digits(base:str) -> typing.Optional[tuple[int, int]]:
    r"""
    Compute check digits for a 12-character CNPJ base.
    Returns `None` if the input is invalid.
    """
    ...

def cnpj_format(cnpj:str) -> typing.Optional[str]:
    r"""
    Format a CNPJ string as `XX.XXX.XXX/XXXX-DD`.
    Returns `None` if the input is not a valid 14-character CNPJ.
    """
    ...

def cnpj_generate(kind:CnpjKind) -> str:
    r"""
    Generate a random valid CNPJ as a 14-character string.
    """
    ...

def cnpj_is_valid(cnpj:str) -> bool:
    r"""
    Lenient CNPJ validation (strips non-alphanumeric characters first).
    """
    ...

def cnpj_is_valid_strict(cnpj:str) -> None:
    r"""
    Strict CNPJ validation (accepts only `XX.XXX.XXX/XXXX-DD` or 14 raw characters).
    """
    ...

def cnpj_remove_symbols(cnpj:str) -> str:
    r"""
    Remove all non-alphanumeric characters from a CNPJ string, uppercase.
    """
    ...

def cpf_compute_check_digits(base:str) -> typing.Optional[tuple[int, int]]:
    r"""
    Compute check digits for a 9-digit CPF base.
    Returns `None` if the input is invalid.
    """
    ...

def cpf_format(cpf:str) -> typing.Optional[str]:
    r"""
    Format a CPF string as `###.###.###-##`.
    Returns `None` if the input doesn't contain exactly 11 digits.
    """
    ...

def cpf_generate() -> str:
    r"""
    Generate a random valid CPF as an 11-digit string.
    """
    ...

def cpf_is_valid(cpf:str) -> bool:
    r"""
    Lenient CPF validation (strips non-digit characters first).
    """
    ...

def cpf_is_valid_strict(cpf:str) -> None:
    r"""
    Strict CPF validation (accepts only `###.###.###-##` or `###########`).
    """
    ...

def cpf_remove_symbols(cpf:str) -> str:
    r"""
    Remove all non-digit characters from a CPF string.
    """
    ...

def municipio_capital_of(state:State) -> Municipio:
    r"""
    Get the capital of a given state.
    """
    ...

def municipio_count() -> int:
    r"""
    Total number of municipalities.
    """
    ...

def municipio_from_ibge_code(code:int) -> typing.Optional[Municipio]:
    r"""
    Find a municipality by its IBGE code.
    """
    ...

def municipio_search_by_name(query:str) -> list[Municipio]:
    r"""
    Find municipalities whose name contains the given substring (case-insensitive).
    """
    ...

def municipios_by_state(state:State) -> list[Municipio]:
    r"""
    Returns all municipalities in a given state.
    """
    ...

def state_abbreviation(state:State) -> str:
    r"""
    Get the abbreviation of a state (e.g. "SP").
    """
    ...

def state_from_abbreviation(abbr:str) -> typing.Optional[State]:
    r"""
    Parse a state from its two-letter abbreviation (case-insensitive).
    """
    ...

def state_name(state:State) -> str:
    r"""
    Get the full name of a state (e.g. "São Paulo").
    """
    ...

def rg_is_valid(rg:str, uf:State) -> bool:
    r"""
    Lenient RG validation for the given UF.
    """
    ...

def rg_is_valid_strict(rg:str, uf:State) -> None:
    r"""
    Strict RG validation for the given UF.
    """
    ...

def rg_format(rg:str, uf:State) -> typing.Optional[str]:
    r"""
    Format an RG string per the UF mask.
    """
    ...

def rg_remove_symbols(rg:str, uf:State) -> str:
    r"""
    Remove all non-digit characters from an RG string.
    """
    ...

def rg_compute_check_digit(base:str, uf:State) -> typing.Optional[int]:
    r"""
    SP-only: compute the check digit for an 8-digit base.
    """
    ...

def rg_generate(uf:State) -> str:
    r"""
    Generate a random valid RG as a string. Currently SP only.
    """
    ...

def state_region(state:State) -> Region:
    r"""
    Get the geographic region of a state.
    """
    ...

