load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@rules_rust//rust:defs.bzl", "rust_shared_library", "rust_static_library")
load("//tools/rules_rust_extras:cbindgen.bzl", "cbindgen")

exports_files([
    "Cargo.toml",
    "include/stdbr.h",
    "test_parity.c",
])

rust_shared_library(
    name = "stdbr-ffi-shared",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    visibility = ["//visibility:public"],
    deps = ["//core:stdbr-core"],
)

rust_static_library(
    name = "stdbr-ffi-static",
    srcs = glob(["src/**/*.rs"]),
    crate_root = "src/lib.rs",
    visibility = ["//visibility:public"],
    deps = ["//core:stdbr-core"],
)

cbindgen(
    name = "stdbr-header-generated",
    srcs = glob(["src/**/*.rs"]),
    config = "cbindgen.toml",
    crate_root = "src/lib.rs",
    header_name = "stdbr.h",
)

cc_library(
    name = "stdbr-header",
    hdrs = ["include/stdbr.h"],
    includes = ["include"],
    visibility = ["//visibility:public"],
)

diff_test(
    name = "stdbr-header-diff-test",
    file1 = "include/stdbr.h",
    file2 = ":stdbr-header-generated",
)
